USE devlens_ai;

CREATE TABLE IF NOT EXISTS users (
  id          CHAR(36)      NOT NULL,
  github_id   VARCHAR(255)  UNIQUE,
  username    VARCHAR(255)  NOT NULL,
  email       VARCHAR(255)  DEFAULT NULL,
  avatar_url  VARCHAR(1000) DEFAULT NULL,
  created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) ENGINE=InnoDB;
